name = "johndegraft-app"
main = ".open-next/worker.js"
compatibility_date = "2026-05-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
